description = "Cloud Native builder for C and C++"

[[buildpacks]]
  uri = "docker://docker.io/bincraft/cmakepack:0.1.0"
  version = "0.1.0"

[[buildpacks]]
  uri = "docker://docker.io/bincraft/conanpack:0.1.0"
  version = "0.1.0"

[[buildpacks]]
  uri = "docker://docker.io/bincraft/mesonpack:0.1.0"
  version = "0.1.0"

[[order]]
  [[order.group]]
    id = "bincraft/conanpack"

[[order]]
  [[order.group]]
    id = "bincraft/mesonpack"

[[order]]
  [[order.group]]
    id = "bincraft/cmakepack"

[build]
  image = "bincraft/hera-builder-base:jammy"
[run]
  [[run.images]]
    image = "bincraft/hera-runner-base:jammy"

[stack]
  id = "net.binarycraft.stacks.hera"
  build-image = "bincraft/hera-builder-base:jammy"
  run-image = "bincraft/hera-runner-base:jammy"
