name: Build
on:
  push:
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            os: ubuntu-latest
          - arch: arm64
            os: macos-latest-xlarge
    runs-on: ${{ matrix.os }}
    env:
      BUILDER_NAME: hera-builder
      BUILDER_VERSION: jammy-${{ matrix.arch }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up pack
        uses: buildpacks/github-actions/setup-pack@v5.5.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create builder ${{ vars.DOCKER_NAMESPACE }}/${{ env.BUILDER_NAME }}:${{ env.BUILDER_VERSION }}
        run: pack builder create ${{ vars.DOCKER_NAMESPACE }}/${{ env.BUILDER_NAME }}:${{ env.BUILDER_VERSION }} --config ./builder.toml

      #- name: Push builder ${{ vars.DOCKER_NAMESPACE }}/${{ env.BUILDER_NAME }}:${{ env.BUILDER_VERSION }} to Docker hub
      #  run: docker push ${{ vars.DOCKER_NAMESPACE }}/${{ env.BUILDER_NAME }}:${{ env.BUILDER_VERSION }}
