name: Build
on:
  push:
    branches-ignore: [main]
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  workflow_dispatch:
env:
  BUILDER_IMAGE: ${{ vars.DOCKER_NAMESPACE }}/hera-builder:jammy
  PACK_VERSION: ${{ vars.PACK_VERSION }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILDER_FULL_IMAGE: ${{ env.BUILDER_IMAGE }}-amd64
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up pack
        run: bash scripts/setup-pack.sh

      - name: Create builder ${{ env.BUILDER_FULL_IMAGE }}
        run: pack builder create ${{ env.BUILDER_FULL_IMAGE }} --config ./builder.toml

      - name: Inspect built image
        run: docker inspect ${{ env.BUILDER_FULL_IMAGE }}
